aws-samples/baseline-environment-on-aws

.github/workflows/build.yml, README.md, README_ja.md
Enable CI workflow using GitHub Actions and add some build badges to README.
This workflow implements basic build steps including lint, test, build, and cdk synth. We can run static checks before pull-request is merged. Workflow runs in below environment:
* Ubuntu + Node.js v14
* Ubuntu + Node.js v16
* Windows + Node.js v14
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> ci: enable GitHub Actions workflow and build badges

.gitlab-ci.yml
Enable CI in GitLab CI. This doesn't work in GitHub, but this is valuable for users who have GitLab.
Note: Environment variables prefixed `AWS_` in GitLab Runner is expressly overriden with zero length string. This is set to prevent commands from unintentionally accessing the AWS environment using container's default credential.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> ci: enable GitLab CI for implementation sample

doc/HowTo.md, doc/HowTo_ja.md
Fix VS Code shortcut key for Mac.
Key for opening Command Palette is `Command + Shift + p`.
--
=> docs: VS Code shortcut key for Mac

usecases/base-ct-guest/lib/blea-security-alarm-stack.ts, usecases/base-standalone/lib/blea-security-alarm-stack.ts
Updated the NIST quick start link as it was not a proper link.
---
=> docs:  fix NIST quick start link in code comments

package-lock.json, package.json
The version specification of typescript in the root directory was different than in the subdirectories, so fix package.json in the root dir and reinstall it.
---
=> build: typescript from 4.4.4 to 4.5.5

.github/workflows/build.yml
CI runs at the timing of the push to any branch of the forked repository to improve the efficiency of development.
---
=> ci: change to trigger CI on push to any branch as well

.github/workflows/build.yml
Changed node version from 14 to 16 in Windows environment for CI. npm update command error occurs when CI is executed with node version 14 due to a bug here(https://github.com/npm/cli/issues/4341). In consideration of the fact that the active node version is 16(https://nodejs.org/en/about/releases/) and that CI runs in node14 in the ubuntu environment, only node16 is sufficient for CI in windows environment.
---
=> ci: change node version of CI's windows environment from 14 to 16

package-lock.json
High severity in `minimist` is reported by `npm audit`
This issue is resolved by `npm audit fix` .
---
--
minimist  <=1.2.5
Severity: high
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist
1 high severity vulnerability
To address all issues, run:
npm audit fix
=> fix: vulnerabilities in minimist

usecases/base-standalone/lib/blea-config-stack.ts, usecases/base-standalone/test/__snapshots__/blea-base-sa.test.ts.snap
※ReOpen PullRequest:#43
Follow the latest version of the IAM policy as the title suggests. The documents I referred to are as follows
https://docs.aws.amazon.com/config/latest/developerguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AWS_ConfigRole
---
=> fix: AWSConfigRole is deprecated. The replacement policy is AWS_ConfigRole.

README.md, README_ja.md, doc/HowTo.md, doc/HowTo_ja.md
A standard for detecting container privileged mode has been added to the AWS Foundational Security Best Practices controls on the Security Hub. When deploying an ECS guest application, this standard is out of compliance, so a guide has been added on how to suppress that warning notification.
---
=> docs: Add a guidance to deal with alerts about codebuild from security hub 

usecases/base-ct-guest/lib/blea-security-alarm-stack.ts, usecases/base-ct-guest/test/__snapshots__/blea-base-ct-guest.test.ts.snap, usecases/base-standalone/lib/blea-security-alarm-stack.ts, usecases/base-standalone/test/__snapshots__/blea-base-sa.test.ts.snap
Exclude calls “Decrypt" event by config.amazonaws.com to ignore innocuous errors caused by AWS Config.
That error occurs when Lambda function has a KMS (CMK) encrypted environment variable.
Sample error logged in CloudTrail:
```
{
"eventVersion": "1.08",
"userIdentity": {
"type": "AssumedRole",
"principalId": "XXXXXXXXXXXXXXXXXXXXX:LambdaDescribeHandlerSession",
-- snip ---
"invokedBy": "config.amazonaws.com"
},
"eventTime": "2021-10-30T02:19:55Z",
"eventSource": "kms.amazonaws.com",
"eventName": "Decrypt",
"awsRegion": "ap-northeast-1",
"sourceIPAddress": "config.amazonaws.com",
"userAgent": "config.amazonaws.com",
"errorCode": "AccessDenied",
"errorMessage": "User: arn:aws:sts::000000000000:assumed-role/aws-controltower-ConfigRecorderRole/LambdaDescribeHandlerSession is not authorized …
```
=> feat: Revise metrics filter for UnauthorizedAttemptsAlarm.

usecases/base-standalone/lib/blea-config-stack.ts, usecases/base-standalone/lib/blea-trail-stack.ts, usecases/base-standalone/test/__snapshots__/blea-base-sa.test.ts.snap, usecases/guest-webapp-sample/lib/blea-vpc-stack.ts, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-asgapp-sample.test.ts.snap, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ec2app-sample.test.ts.snap, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ecsapp-sample.test.ts.snap, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ecsapp-ssl-sample.test.ts.snap
I noticed some buckets with and without "enforceSSL = true". I also found places where L1 was used without using L2Construct, but these seemed to be inevitable, so I fixed them as well.
---
=> Hotfix: bucket-enforce-ssl

usecases/guest-webapp-sample/lib/blea-vpc-stack.ts
Subnet type `PRIVATE` and `ISOLATED` are deprecated. Replaced them with `PRIVATE_WITH_NAT` and `PRIVATE_ISOLATED`
---
=> fix: Replaced subnet type PRIVATE and ISOLATED with PRIVATE_WITH_NAT and PRIVATE_ISOLATED

doc/Standalone2ControlTower_ja.md
Fix image path
- before
https://github.com/aws-samples/baseline-environment-on-aws/blob/323662f430dc281a9aead5cb26d3d4efb40ce7f9/doc/Standalone2ControlTower_ja.md#21-aws-config-delivery-channel-%E3%82%92%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B
- after 
https://github.com/koudaiii/baseline-environment-on-aws/blob/2e57e2dcf834cc913f6ac5c85ff4dd74d6903e1f/doc/Standalone2ControlTower_ja.md#21-aws-config-delivery-channel-%E3%82%92%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B
---
=> Fix image path in Migrate BLEA Standalone to BLEA Multi-Account(ja)

doc/DeployToControlTower.md, doc/HowTo.md, doc/HowTo_ja.md, doc/PipelineDeployment.md, doc/PipelineDeployment_ja.md
I checked all the `.md` files. I think all invalid links have been fixed.
see https://github.com/aws-samples/baseline-environment-on-aws/pull/57
---
=> fix: invalid links and image paths in docs

doc/HowTo.md, doc/HowTo_ja.md
Fix image path
- before
https://github.com/aws-samples/baseline-environment-on-aws/blob/1df2898abc9769d926617ae548f1d5af27979097/doc/HowTo_ja.md#1-cloudshell-%E3%82%92%E8%B5%B7%E5%8B%95%E3%81%99%E3%82%8B
https://github.com/aws-samples/baseline-environment-on-aws/blob/1df2898abc9769d926617ae548f1d5af27979097/doc/HowTo_ja.md#3-cdk-%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E3%81%99%E3%82%8B
https://github.com/aws-samples/baseline-environment-on-aws/blob/1df2898abc9769d926617ae548f1d5af27979097/doc/HowTo.md#1-start-cloudshell
https://github.com/aws-samples/baseline-environment-on-aws/blob/1df2898abc9769d926617ae548f1d5af27979097/doc/HowTo.md#3-upload-cdk-code
- after
---
By submitting this pull request, I confirm that my contribution is made …
=> docs: Fix image path(en and ja)

.github/dependabot.yml
To follow AWS CDK's updates automatically, enable Dependabot.
---
=> ci: Enable Dependabot to update deps weekly

.github/workflows/pr-auto-merge.yml
Enable auto-merge for Dependabot's PR which updates minor or patch version. Major updates still should be reviewed.
---
=> ci: Auto-merge dependabot's PR

.github/workflows/build.yml
Prevent running GitHub Actions twice when dependabot pushes new branches in this repository.
This reverts commit ac938655fa05c7888f78f4417129643a8ec1fcf9.
---
=> Revert "ci: github actions to be triggered by push to all branches (#40)"

doc/DeployToControlTower.md, doc/DeployToControlTower_ja.md, doc/PipelineDeployment.md, doc/PipelineDeployment_ja.md
This commit update docs to use AWS SSO credential without aws-wrap. This feature is available on CDK v2.18.0 and later.
---
=> doc: Update docs to use AWS SSO credential directly

usecases/guest-webapp-sample/lib/blea-vpc-stack.ts
PRIVATE_WITH_NAT has been deprecated since v2.41.0.
In this PR, PRIVATE_WITH_NAT is changed to PRIVATE_WITH_EGRESS.
References
https://github.com/aws/aws-cdk/releases/tag/v2.41.0
https://github.com/aws/aws-cdk/issues/21699
=> refactor: Update subnet type, PRIVATE_WITH_NAT is deprecated.

usecases/guest-webapp-sample/lib/blea-db-aurora-pg-stack.ts, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-asgapp-sample.test.ts.snap, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ec2app-sample.test.ts.snap, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ecsapp-sample.test.ts.snap, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ecsapp-ssl-sample.test.ts.snap
In guest-webapp-sample, Identifier of RDS Instance was constant string 'instance'. When multiple db stack was created, identifier was possible to conflict. So, identifier is changed to stack-name to set unique name.
---
=> fix: change guest web db identifier

usecases/guest-webapp-sample/lib/blea-ecsapp-stack.ts, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ecsapp-sample.test.ts.snap, usecases/guest-webapp-sample/test/__snapshots__/blea-guest-ecsapp-ssl-sample.test.ts.snap
Currently, imageScanonPush is not enabled for ECR repositories created by pull through cache.
This PR enables ImageScanonPush for ECR repository.
=> feat: enable scan on push with pull through cache

.github/dependabot.yml
Because of throttling, increase limits of PR.
---
=> ci: increase dependabot PR limits

.github/workflows/pr-bot-snapshot-update.yml
To make updating snapshot easy, add a PR bot. The bot is triggerd by commenting `/snapshot update` in PR, and it pulls the branch and do `npm test --workspaces -- -u`, then commit and push it.
---
=> ci: add bot to update shapshot test in PR

usecases/blea-guest-ecs-app-sample/lib/construct/frontend.ts, usecases/blea-guest-ecs-app-sample/test/__snapshots__/blea-guest-ecs-app-sample.test.ts.snap
Fix #363.
Added `ObjectOwnership` property to the bucket that stores CloudFront access logs.
---
=> fix: add ObjectOwnership property

usecases/blea-guest-ecs-app-sample/lib/construct/dashboard.ts, usecases/blea-guest-ecs-app-sample/test/__snapshots__/blea-guest-ecs-app-sample.test.ts.snap
Some CloudWatch Metrics seem to have incorrect names.
---
=> fix: metrics name

usecases/blea-guest-serverless-api-sample/lib/construct/lambda-nodejs.ts, usecases/blea-guest-serverless-api-sample/lib/construct/lambda-python.ts, usecases/blea-guest-serverless-api-sample/test/__snapshots__/blea-guest-apiapp-nodejs-sample.test.ts.snap
Update the outdated version of the Lambda Runtime within the blea-guest-serverless-api-sample.
- NODEJS_14_X to NODEJS_LATEST(now NODEJS_18_X)
- PYTHON_3_7 to PYTHON_3_12
- Update the Layer to use Powertools compatible with Python 3.12.
- Deploy the resources and send a request to the endpoint. Verify that a successful response is returned.
```
curl -X POST https://xxxxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/prod/nodejs/item -d '{"title":"hoge","content":"body desu"}'
"Success to putItem to the DynamoDB"
curl https://xxxxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/prod/nodejs/list                                               
[{"content":{"S":"body desu"},"title":{"S":"hoge"},"created_at":{"S":"Thu Jun 13 2024 06:51:33 GMT+0000 (Coordinated Universal Time)"}}]% 
curl …
```
=> fix(blea-guest-serverless-api-sample): lambda runtime version and snapshot update

.eslintrc.json
When lint-staged runs `eslint --fix`, we get the error: 
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
To avoid this, set a parser option to ESLint.
https://github.com/typescript-eslint/typescript-eslint/issues/1192#issuecomment-2071711326
---
=> build: Avoid ESLint OOM

usecases/blea-gov-base-ct/jest.config.js, usecases/blea-gov-base-ct/test/__snapshots__/blea-gov-base-ct-via-service-catalog.test.ts.snap, usecases/blea-gov-base-ct/test/plugin/ignore-assets-snapshot-selializer.ts, usecases/blea-gov-base-standalone/jest.config.js, usecases/blea-gov-base-standalone/test/plugin/ignore-assets-snapshot-selializer.ts, usecases/blea-guest-ec2-app-sample/jest.config.js, usecases/blea-guest-ec2-app-sample/test/plugin/ignore-assets-snapshot-selializer.ts, usecases/blea-guest-ecs-app-sample/jest.config.js, usecases/blea-guest-ecs-app-sample/test/__snapshots__/blea-guest-ecs-app-sample.test.ts.snap, usecases/blea-guest-ecs-app-sample/test/plugin/ignore-assets-snapshot-selializer.ts, usecases/blea-guest-serverless-api-sample/jest.config.js, usecases/blea-guest-serverless-api-sample/test/__snapshots__/blea-guest-apiapp-nodejs-sample.test.ts.snap, usecases/blea-guest-serverless-api-sample/test/plugin/ignore-assets-snapshot-selializer.ts
In this repository, Dependabot automatically updates dependent packages. However, when AWS SDK, X-Ray, and others are updated, asset hash of Lambda functions changes, making it impossible to merge automatically. To avoid this, using Jest's functionality to replace asset hash with a fixed string in snapshot tests.
---
=> build: Ignore asset changes in snapshot tests

knip.config.ts
When we migrated `depcheck` to `knip` in #924 , we forgot to remove `prettier` and `eslint` from `ignoreDependencies` in `knip.config.ts`. Therefore I've removed them.
ref: https://github.com/aws-samples/baseline-environment-on-aws/pull/924#pullrequestreview-2490925750
---
=> fix: rm eslint & prettier from ignoreDependencies in knip config
